site_name: My Docs
theme:
  name: material

markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        - name: openqasm
          class: openqasm
          format: !!python/name:ftqcwiki.format_openqasm
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
